Repository platzimaster-wedeal/wefront, pull requests merged in 2020-09, with the labels that each got.

#31 [REFACTOR] ButtonAction component added
  .eslintrc.json
  src/assets/styles/components/Button/Button.scss
  src/assets/styles/components/Buttons/ButtonAction.scss
  src/assets/styles/components/Buttons/SmallButtonCA.scss
  src/assets/styles/components/Buttons/SmallButtonSA.scss
  src/assets/styles/components/Draw/Draw.scss
  src/components/Button/Button.jsx
  src/components/Buttons/ButtonAction.jsx
  src/components/Buttons/SmallButtonCA.jsx
  src/components/Buttons/SmallButtonSA.jsx
  src/container/Draw.js
Labels: Structure

#32 [REFACTOR] SmallButtonCA and SmallButtonSA added
  src/assets/styles/components/Buttons/SmallButtonCA.scss
  src/assets/styles/components/Buttons/SmallButtonSA.scss
  src/assets/styles/components/Draw/Draw.scss
  src/components/Buttons/SmallButtonCA.jsx
  src/components/Buttons/SmallButtonSA.jsx
  src/container/Draw.js
Labels: Structure

#34 ➕ ADD: label component added ♻️ REFACTOR: Draw Container styles refa…
  src/assets/styles/components/Draw/Draw.scss
  src/assets/styles/components/Label/Label.scss
  src/components/Labels/Labels.jsx
  src/container/Draw.js
Labels: Structure

#36 [♻️ REFACTOR] Button component added [🛠 FIX] Code has been formatted
  src/assets/styles/components/Buttons/Button.scss
  src/components/Buttons/Button.jsx
  src/components/Buttons/SmallButtonSA.jsx
  src/components/Labels/Labels.jsx
  src/container/Draw.js
Labels: Structure

#40 [ADD] Feature/problem previsualization
  src/assets/styles/App.scss
  src/assets/styles/components/problemPrevisualization/ProblemPrevisualization.scss
  src/assets/styles/partials/text.scss
  src/components/ProblemPrevisualization/ProblemPrevisualization.jsx
Labels: Structure

#41 [ADD] component/ProblemStatus
  src/assets/styles/components/ProblemStatus/ProblemStatus.scss
  src/components/ProblemStatus/ProblemStatus.jsx
Labels: Structure

#43 ➕ [ADD] requirements component added
  src/assets/styles/components/Requirements/Requirements.scss
  src/components/Requirements/Requirements.jsx
  src/container/Draw.js
Labels: Structure, help

#42 [➕ADD] ProfilePicture component added
  src/assets/static/img/julio.jpg
  src/assets/styles/components/ProfilePicture/ProfilePicture.scss
  src/components/ProfilePictures/ProfilePicture.jsx
  src/container/Draw.js
Labels: Structure

#44 Feature/graphic data
  src/assets/styles/App.scss
  src/assets/styles/components/Draw/Draw.scss
  src/assets/styles/components/GraphicData/Followers.scss
  src/assets/styles/components/GraphicData/Location.scss
  src/assets/styles/components/Requirements/Requirements.scss
  src/assets/styles/partials/text.scss
  src/components/GraphicData/Followers.jsx
  src/components/GraphicData/Location.jsx
  src/container/Draw.js
Labels: Structure, bug

#45 [➕ADD] Jest implementation [♻️ REFACTOR] Eslint improved
  .eslintrc.json
  babel.config.js
  package.json
  src/__mocks__/ProviderMock.js
  src/__mocks__/styleMock.js
  src/__test__/components/Buttons/Button.test.js
  src/__test__/components/Buttons/__snapshots__/Button.test.js.snap
  src/__test__/setupTest.js
  webpack.config.js
Labels: Functionality, bug

#49 Feature/interactions post
  package-lock.json
  package.json
  src/assets/styles/components/InteractionsPost/InteractionsPost.scss
  src/components/InteractionsPost/InteractionsPost.jsx
Labels: Structure

#52 [ADD][REFACTOR] - Created the component ProfileHeader
  package.json
  src/__test__/components/ProfileHeader/ProfileHeader.test.js
  src/__test__/components/ProfileHeader/__snapshots__/ProfileHeader.test.js.snap
  src/__test__/components/ProfileHeaderPhoto/ProfileHeaderPhoto.test.js
  src/__test__/components/ProfileHeaderPhoto/__snapshots__/ProfileHeaderPhoto.test.js.snap
  src/assets/static/img/users/user.jpg
  src/assets/static/img/users/visitor.jpg
  src/assets/styles/App.scss
  src/assets/styles/components/Buttons/Button.scss
  src/assets/styles/components/ProfileHeader/ProfileHeader.scss
  src/assets/styles/components/ProfileHeaderPhoto/ProfileHeaderPhoto.scss
  src/components/Buttons/Button.jsx
  src/components/Buttons/ButtonAction.jsx
  src/components/Buttons/SmallButtonCA.jsx
  src/components/Buttons/SmallButtonSA.jsx
  src/components/GraphicData/Followers.jsx
  src/components/GraphicData/Location.jsx
  src/components/ProfileHeader/ProfileHeader.jsx
  src/components/ProfileHeaderActions/ProfileHeaderActions.jsx
  src/components/ProfileHeaderPhoto/ProfileHeaderPhoto.jsx
  src/components/Requirements/Requirements.jsx
Labels: Structure, test

#55 [ADD] - PostHeader component created
  src/__test__/components/PostHeader/PostHeader.test.js
  src/__test__/components/PostHeader/__snapshots__/PostHeader.test.js.snap
  src/__test__/components/ProfileHeader/__snapshots__/ProfileHeader.test.js.snap
  src/assets/styles/components/PostHeader/PostHeader.scss
  src/components/InteractionsPost/InteractionsPost.jsx
  src/components/PostHeader/PostHeader.jsx
Labels: Structure, test

#56 [REFACTOR] - Modify the name and a little of InteractionPost
  src/assets/styles/components/InteractionsPost/InteractionsPost.scss
  src/assets/styles/components/PostInteractions/PostInteractions.scss
  src/components/PostInteractions/PostInteractions.jsx
Labels: Structure

#64 [ADD][REFACTOR] - Create the component PostShare with responsive and …
  src/__test__/components/PostShare/PostShare.test.js
  src/__test__/components/PostShare/__snapshots__/PostShare.test.js.snap
  src/assets/styles/components/InteractionsPost/InteractionsPost.scss
  src/assets/styles/components/PostShare/PostShare.scss
  src/components/PostShare/PostShare.jsx
Labels: Structure, test

#66 [ADD][REFACTOR] - PostProblem created, with responsive and tests :D
  src/__test__/components/PostHeader/__snapshots__/PostHeader.test.js.snap
  src/__test__/components/PostProblem/PostProblem.test.js
  src/__test__/components/PostProblem/__snapshots__/PostProblem.test.js.snap
  src/assets/styles/components/GraphicData/GraphicData.scss
  src/assets/styles/components/Label/Label.scss
  src/assets/styles/components/PostHeader/PostHeader.scss
  src/assets/styles/components/PostProblem/PostProblem.scss
  src/components/PostHeader/PostHeader.jsx
  src/components/PostProblem/PostProblem.jsx
Labels: Structure, test

#71 [ADD] - Created PostProblemDescription component :D
  src/__test__/components/PostProblemDescription/PostProblemDescription.test.js
  src/__test__/components/PostProblemDescription/__snapshots__/PostProblemDescription.test.js.snap
  src/assets/styles/components/PostProblemDescription/PostProblemDescription.scss
  src/components/PostProblemDescription/PostProblemDescription.jsx
Labels: Structure, test

#72 [ADD][REFACTOR] - Created PostProblemRequirements Component :D
  src/__test__/components/PostProblemRequirements/PostProblemRequirements.test.js
  src/__test__/components/PostProblemRequirements/__snapshots__/PostProblemRequirements.test.js.snap
  src/assets/styles/components/PostProblemRequirements/PostProblemRequirements.scss
  src/assets/styles/components/Requirements/Requirements.scss
  src/components/PostProblemRequirements/PostProblemRequirements.jsx
Labels: Structure, test

#74 [ADD] - Created the Layout Of Containers of the website with Mobile v…
  src/assets/styles/layouts/ChangeView/ChangeView.scss
  src/layouts/ChangeView/ChangeView.jsx
Labels: Structure

#75 Feature/general information
  src/__test__/components/GeneralInformation/GeneralInformation.test.js
  src/__test__/components/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
  src/assets/styles/components/GeneralInformation/GeneralInformation.scss
  src/components/GeneralInformation/GeneralInformation.jsx
Labels: Structure, help, test

#60 [➕ADD] StrategyCard component added [♻️ REFACTOR] ButtonAction compon…
  src/assets/styles/components/Draw/Draw.scss
  src/assets/styles/components/StrategyCard/StrategyCard.scss
  src/components/Buttons/ButtonAction.jsx
  src/components/ProfilePictures/ProfilePicture.jsx
  src/components/StrategyCard/StrageyCard.jsx
  src/container/Draw.js
Labels: Structure, bug

#77 [ADD] - Created FeedGeneral component as all the Feeds in the project
  src/assets/styles/components/FeedGeneral/FeedGeneral.scss
  src/components/FeedGeneral/FeedGeneral.jsx
  src/components/PostDefineType/PostDefineType.jsx
  src/components/PostProblem/PostProblem.jsx
Labels: Structure

#80 [➕ADD] PersonCard componend added [♻️ REFACTOR] All buttons with resp…
  .eslintrc.json
  src/assets/styles/App.scss
  src/assets/styles/components/Buttons/Button.scss
  src/assets/styles/components/Buttons/ButtonAction.scss
  src/assets/styles/components/Buttons/SmallButtonCA.scss
  src/assets/styles/components/Buttons/SmallButtonSA.scss
  src/assets/styles/components/PersonCard/PersonCard.scss
  src/assets/styles/components/StrategyCard/StrategyCard.scss
  src/assets/styles/partials/buttons.scss
  src/components/Buttons/Button.jsx
  src/components/Buttons/SmallButtonCA.jsx
  src/components/Buttons/SmallButtonSA.jsx
  src/components/PersonCard/PersonCard.jsx
  src/components/ProfilePictures/ProfilePicture.jsx
  src/container/Draw.js
Labels: Structure, bug

#81 [ADD] - Created WorkerInformation with responsive and tests
  src/__test__/components/GeneralInformation/GeneralInformation.test.js
  src/__test__/components/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
  src/__test__/components/PostShare/__snapshots__/PostShare.test.js.snap
  src/__test__/components/WorkerInformation/WorkerInformation.test.js
  src/__test__/components/WorkerInformation/__snapshots__/WorkerInformation.test.js.snap
  src/__test__/components/WorkerMainInformation/WorkerMainInformation.test.js
  src/__test__/components/WorkerMainInformation/__snapshots__/WorkerMainInformation.test.js.snap
  src/assets/styles/components/GraphicData/GraphicData.scss
  src/assets/styles/components/WorkerInformation/WorkerInformation.scss
  src/assets/styles/components/WorkerMainInformation/WorkerMainInformation.scss
  src/components/GeneralInformation/GeneralInformation.jsx
  src/components/WorkerInformation/WorkerInformation.jsx
  src/components/WorkerMainInformation/WorkerMainInformation.jsx
Labels: Structure, test

#84 [➕ADD] ProfileSmallCard component added
  src/assets/styles/components/Draw/Draw.scss
  src/assets/styles/components/PersonCard/PersonCard.scss
  src/assets/styles/components/ProfileSmallCard/ProfileSmallCard.scss
  src/components/PersonCard/PersonCard.jsx
  src/components/ProfileSmallCard/ProfileSmallCard.jsx
  src/container/Draw.js
Labels: Structure, help

#86 Feature/select profile type
  src/assets/styles/components/SelectProfileType/SelectProfileType.scss
  src/components/SelectProfileType/SelectProfileType.jsx
  src/container/Draw.js
Labels: Structure

#89 [➕ADD] AlertProfileConf component added - [🛠 FIX] Code has been formatted.
  src/assets/styles/components/AlertProfileConf/AlertProfileConf.scss
  src/components/AlertProfileConf/AlertProfileConf.jsx
  src/container/Draw.js
Labels: Structure

#93 [ADD] - Created the SelectCategories component with responsive and tests
  src/__test__/components/Buttons/__snapshots__/Button.test.js.snap
  src/__test__/components/PostProblem/__snapshots__/PostProblem.test.js.snap
  src/__test__/components/PostProblemDetail/__snapshots__/PostProblemDetail.test.js.snap
  src/__test__/components/ProfileHeader/__snapshots__/ProfileHeader.test.js.snap
  src/__test__/components/ProfileHeaderPhoto/__snapshots__/ProfileHeaderPhoto.test.js.snap
  src/__test__/components/SelectCategories/SelectCategories.test.js
  src/__test__/components/SelectCategories/__snapshots__/SelectCategories.test.js.snap
  src/assets/styles/components/SelectCategories/SelectCategories.scss
  src/components/SelectCategories/SelectCategories.jsx
  src/container/Draw.js
Labels: Structure, test

#109 [ADD][REFACTOR] - Created all components about message and comments :D
  src/__test__/components/ProfileProblems/ProfileProblemsContainer.test.js
  src/__test__/components/ProfileProblems/ProfileProblemsItems.test.js
  src/assets/styles/components/MessageActions/MessageActions.scss
  src/assets/styles/components/PostComments/PostComments.scss
  src/assets/styles/components/PostMessage/PostMessage.scss
  src/assets/styles/components/ProfilePicture/ProfilePicture.scss
  src/assets/styles/partials/colors.scss
  src/components/Message/Message.jsx
  src/components/MessageActions/MessageActions.jsx
  src/components/PostComments/PostComments.jsx
  src/components/PostShare/PostShare.jsx
  src/components/ProfileProblems/ProfileProblemsContainer.jsx
  src/container/Draw.js
Labels: Structure

#111 Feature/select degree type
  src/assets/styles/components/SelectDegreeType/SelectDegreeType.scss
  src/components/SelectDegreeType/SelectDegreeType.jsx
Labels: Structure

#112 [ADD] Feature/profile worker card
  src/__test__/components/PostShare/__snapshots__/PostShare.test.js.snap
  src/__test__/components/ProfileWorkerCard/ProfileWorkerCard.test.js
  src/__test__/components/ProfileWorkerCard/__snapshots__/ProfileWorkerCard.test.js.snap
  src/assets/styles/components/ProfileWorkerCard/ProfileWorkerCard.scss
  src/components/ProfileWorkerCard/ProfileWorkerCard.jsx
Labels: Structure, test

#119 [ADD] - Craeted PorblemStatusCard with test and responsive
  src/__test__/components/ProblemStatusCard/ProblemStatusCard.test.js
  src/__test__/components/ProblemStatusCard/__snapshots__/ProblemStatusCard.test.js.snap
  src/assets/styles/components/ProblemStatusCard/ProblemStatusCard.scss
  src/components/ProblemStatus/ProblemStatus.jsx
  src/components/ProblemStatusCard/ProblemStatusCard.jsx
Labels: Structure, test

#120 [ADD][REFACTORE] - Feature/header search filters
  src/__test__/components/HeaderSearchFilters/HeaderSearchFilters.test.js
  src/__test__/components/HeaderSearchFilters/__snapshots__/HeaderSearchFilters.test.js.snap
  src/__test__/components/PostProblemDetail/PostProblemDetail.test.js
  src/__test__/components/PostProblemDetail/__snapshots__/PostProblemDetail.test.js.snap
  src/assets/styles/components/HeaderSearchFilters/HeaderSearchFilters.scss
  src/components/HeaderSearchFilters/HeaderSearchFilters.jsx
Labels: Structure, test

#124 [ADD][REFACTOR] - Created HeaderSearchResults with responsive and tests
  src/__test__/components/HeaderSearchResults/HeaderSearchResults.test.js
  src/__test__/components/HeaderSearchResults/__snapshots__/HeaderSearchResults.test.js.snap
  src/__test__/components/PostProblemDetail/PostProblemDetail.test.js
  src/assets/styles/components/HeaderSearchResults/HeaderSearchResults.scss
  src/assets/styles/components/PersonCard/PersonCard.scss
  src/assets/styles/components/ProfileSmallCard/ProfileSmallCard.scss
  src/components/HeaderSearchResults/HeaderSearchResults.jsx
Labels: Structure, test

#126 Feature/date picker
  package-lock.json
  package.json
  src/assets/styles/components/DatePicker/SelectDate.scss
  src/components/DatePicker/SelectDate.js
  src/components/SelectDate.js
  src/container/Signup1.js
Labels: Structure
